image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  GIT_DEPTH: 0
  LAB_MANAGER_IMAGE: lab-manager


stages:
  - build-app

# Push lab-front image to the docker registry using Dockerfile of the lab-front
build-app:
  stage: build-app
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # Read the commit tag
    - export VERSION=$CI_COMMIT_TAG
    # Build the docker image from Dockerfile with the tag of the git tag
    - docker build --build-arg LAB_MANAGER_VERSION=$CI_COMMIT_TAG --tag $CI_REGISTRY_IMAGE/$LAB_MANAGER_IMAGE:$VERSION . -f Dockerfile
    # Push image in the registry
    - docker push $CI_REGISTRY_IMAGE/$LAB_MANAGER_IMAGE:$VERSION
  only:
    - tags


