version: "3"

services:

  # GWS Core Production DB
  gws_core_prod_db:
    image: mariadb:10
#    command: --max_allowed_packet=256M
    environment:
      - MYSQL_ROOT_PASSWORD=gencovery
      - MYSQL_USER=gws_core
      - MYSQL_PASSWORD=gencovery
      - MYSQL_DATABASE=gws_core
#    volumes:
#      - /app/prod/data/gws_core/mariadb:/var/lib/mysql
    networks:
      - super-test

networks:
  super-test:
    external: false