version: "3"

services:

  # Production Glab
  lab_manager:
    image: registry.gitlab.com/gencovery/infra/lab-manager/lab-manager:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /app/conf:/app/conf
    environment:
      - VOLUME_PATH=/app/conf
      - GWS_GIT_LOGIN=astroboygencovery
      - GWS_GIT_PWD=plHjfdrnpL%26JJ9h2RMKYQtuLHUYvHQ8ZzU%23yUWm%26
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - DOCKER_REGISTRY_PWD=mmDyQMy3GPoiy_Q63X2Y
      - DOCKER_REGISTRY_USERNAME=gencovery-reader
      - DOCKER_REGISTRY_URL=registry.gitlab.com
    labels:
      - "traefik.enable=true"
      # Config for the HTTPS glab domain to port 3010
      - "traefik.http.routers.lab-manager-router.rule=host(`lab-manager.${VIRTUAL_HOST}`)"
      - "traefik.http.routers.lab-manager-router.service=lab-manager-service"
      - "traefik.http.services.lab-manager-service.loadbalancer.server.port=3010"
      # Enable HTTPS
      - "traefik.http.routers.lab-manager-router.entrypoints=websecure"
      - "traefik.http.routers.lab-manager-router.tls.certresolver=myresolver"
    networks:
      - gencovery-network-manager
    restart: always
    container_name: lab_manager

  # Traefik reverse proxy
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.4
    command:
      # So that Traefik can listen to the Docker events
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # Enable HTTPS
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # Email for let's encrypt
      - "--certificatesresolvers.myresolver.acme.email=admin@gencovery.com"
      # Json file to store certificate
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

      # Redirect HTTP to HTTPS
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      # Volume to store the lets encrypt certificats
      - /srv/letsencrypt:/letsencrypt
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gencovery-network-manager
      - gencovery-network-dev
      - gencovery-network-prod
    container_name: reverse_proxy

networks:
  gencovery-network-manager:
    external: true
  gencovery-network-dev:
    external: true
  gencovery-network-prod:
    external: true
