services:
  adminer:
    image: adminer:5.4.1
    container_name: ${CONTAINER_PREFIX}-adminer
    networks:
      - ${LAB_NETWORK}
    x-gws-config:
      - https:
          name: adminer
          subDomain: adminer
          internalPort: 8080
          localhostHostPort: 8081
