
services:
  # /!\ WARNING /!\
  # As docker execute inside a docker container, the volume here are relative to the host machine and not the container
  # On /app/prod/lab:/lab, /app/prod/lab refers to the host machine and not the container that run the docker-compose
  # Production Glab
  glab:
    image: registry.gitlab.com/constellab/public/docker-registry/glab-${IMAGE_SUFFIX}:${GLAB_TAG}
    environment:
      - LAB_ID=${LAB_ID}
      - LAB_NAME=${LAB_NAME}
      - LAB_MODE=prod
      - LAB_ENVIRONMENT=ON_CLOUD
      - LAB_PROD_API_URL=https://glab.${VIRTUAL_HOST}
      - LAB_DEV_API_URL=https://glab-dev.${VIRTUAL_HOST}
      - SPACE_API_KEY=${SPACE_API_KEY}
      - SPACE_API_URL=${SPACE_API_URL}
      - SPACE_FRONT_URL=${SPACE_FRONT_URL}
      # TODO TO REMOVE ONCE all lab are on v0.8.2
      - CENTRAL_API_KEY=${SPACE_API_KEY}
      - CENTRAL_API_URL=${SPACE_API_URL}
      # end remove
      - FRONT_URL=https://front.${VIRTUAL_HOST}
      - FRONT_VERSION=${FRONT_VERSION}
      - GPU=${GPU}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - BIOTA_BIODATA_DIR=/data/gws_biota/biodata/
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # COMMUNITY
      - COMMUNITY_API_URL=${COMMUNITY_API_URL}
      - COMMUNITY_FRONT_URL=${COMMUNITY_FRONT_URL}
      - COMMUNITY_API_KEY=${COMMUNITY_API_KEY}
      # GWS_CORE database
      - GWS_CORE_DB_HOST=gws_core_prod_db
      - GWS_CORE_DB_USER=gws_core
      - GWS_CORE_DB_PASSWORD=${GWS_CORE_PROD_DB_PASSWORD}
      - GWS_CORE_DB_NAME=gws_core
      - GWS_CORE_DB_PORT=3306
      # GWS_BIOTA database
      - GWS_BIOTA_DB_HOST=gws_biota_db
      - GWS_BIOTA_DB_USER=gws_biota
      - GWS_BIOTA_DB_PASSWORD=gencovery
      - GWS_BIOTA_DB_NAME=gws_biota
      - GWS_BIOTA_DB_PORT=3306
      # STREAMLIT 
      - STREAMLIT_APP_SERVER_PORT=8501
      - STREAMLIT_APP_SERVER_HOST=https://dashboard.${VIRTUAL_HOST}
    depends_on:
      - gws_core_prod_db
    volumes:
      - /app/prod/lab:/lab
      - /app/prod/logs:/logs
      - /app/prod/settings/glab:/conf/settings
      - /app/conf/config.json:/conf/config.json:ro
      - /app/prod/data:/data
    labels:
      - "traefik.enable=true"
      # Config for the HTTPS glab domain to port 8080
      - "traefik.http.routers.glab-router.rule=host(`glab.${VIRTUAL_HOST}`)"
      - "traefik.http.routers.glab-router.service=glab-service"
      - "traefik.http.services.glab-service.loadbalancer.server.port=3000"
      # Enable HTTPS
      - "traefik.http.routers.glab-router.entrypoints=websecure"
      - "traefik.http.routers.glab-router.tls.certresolver=myresolver"
      # Config for https streamlit domain to port 8501
      - "traefik.http.routers.streamlit-router.rule=host(`dashboard.${VIRTUAL_HOST}`)"
      - "traefik.http.routers.streamlit-router.service=streamlit-service"
      - "traefik.http.services.streamlit-service.loadbalancer.server.port=8501"
      # Enable HTTPS
      - "traefik.http.routers.streamlit-router.entrypoints=websecure"
      - "traefik.http.routers.streamlit-router.tls.certresolver=myresolver"
    networks:
      - gencovery-network-prod
    restart: on-failure:5
    container_name: glab
    #GPU_CONFIG#

  # Codelab
  codelab:
    image: registry.gitlab.com/constellab/public/docker-registry/codelab-${IMAGE_SUFFIX}:${GLAB_TAG}
    environment:
      - LAB_ID=${LAB_ID}
      - LAB_NAME=${LAB_NAME}
      - LAB_MODE=dev
      - LAB_ENVIRONMENT=ON_CLOUD
      - LAB_PROD_API_URL=https://glab.${VIRTUAL_HOST}
      - LAB_DEV_API_URL=https://glab-dev.${VIRTUAL_HOST}
      - FRONT_URL=https://front.${VIRTUAL_HOST}
      - FRONT_VERSION=${FRONT_VERSION}
      - GPU=${GPU}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - BIOTA_BIODATA_DIR=/data/gws_biota/biodata/
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # COMMUNITY
      - COMMUNITY_API_URL=${COMMUNITY_API_URL}
      - COMMUNITY_FRONT_URL=${COMMUNITY_FRONT_URL}
      - COMMUNITY_API_KEY=${COMMUNITY_API_KEY}
      # GWS_CORE database
      - GWS_CORE_DB_HOST=gws_core_dev_db
      - GWS_CORE_DB_USER=gws_core
      - GWS_CORE_DB_PASSWORD=${GWS_CORE_DEV_DB_PASSWORD}
      - GWS_CORE_DB_NAME=gws_core
      - GWS_CORE_DB_PORT=3306
      # Test database
      - GWS_TEST_DB_HOST=test_gws_dev_db
      - GWS_TEST_DB_USER=test_gws
      - GWS_TEST_DB_PASSWORD=gencovery
      - GWS_TEST_DB_NAME=test_gws
      - GWS_TEST_DB_PORT=3306
      # GWS_BIOTA database
      - GWS_BIOTA_DB_HOST=gws_biota_db
      - GWS_BIOTA_DB_USER=gws_biota
      - GWS_BIOTA_DB_PASSWORD=gencovery
      - GWS_BIOTA_DB_NAME=gws_biota
      - GWS_BIOTA_DB_PORT=3306
      # STREAMLIT 
      - STREAMLIT_APP_SERVER_PORT=8501
      - STREAMLIT_APP_SERVER_HOST=https://dashboard-dev.${VIRTUAL_HOST}
    depends_on:
      - gws_core_dev_db
    volumes:
      - /app/dev/lab:/lab
      - /app/dev/logs:/logs
      - /app/dev/data:/data
      - /app/dev/settings/glab:/conf/settings
      - /app/conf/config.json:/conf/config.json:ro
      - /app/dev/.ssh:/root/.ssh
    labels:
      - "traefik.enable=true"
      # Config for the HTTPS codelab domain to port 8080
      - "traefik.http.routers.codelab-router.rule=host(`codelab.${VIRTUAL_HOST}`)"
      - "traefik.http.routers.codelab-router.service=codelab-service"
      - "traefik.http.services.codelab-service.loadbalancer.server.port=8080"
      # Enable HTTPS
      - "traefik.http.routers.codelab-router.entrypoints=websecure"
      - "traefik.http.routers.codelab-router.tls.certresolver=myresolver"
      # secure the access with htpasswd
      - "traefik.http.routers.codelab-router.middlewares=basic-auth"
      - "traefik.http.middlewares.basic-auth.basicauth.users=${HT_PASSWD}"

      # Config for the HTTPS gws run inside the CODELAB domain to port 3000
      - "traefik.http.routers.glab-dev-router.rule=host(`glab-dev.${VIRTUAL_HOST}`)"
      - "traefik.http.routers.glab-dev-router.service=glab-dev-service"
      - "traefik.http.services.glab-dev-service.loadbalancer.server.port=3000"
      # Enable HTTPS
      - "traefik.http.routers.glab-dev-router.entrypoints=websecure"
      - "traefik.http.routers.glab-dev-router.tls.certresolver=myresolver"

      # Config for https streamlit domain to port 8501
      - "traefik.http.routers.streamlit-dev-router.rule=host(`dashboard-dev.${VIRTUAL_HOST}`)"
      - "traefik.http.routers.streamlit-dev-router.service=streamlit-dev-service"
      - "traefik.http.services.streamlit-dev-service.loadbalancer.server.port=8501"
      # Enable HTTPS
      - "traefik.http.routers.streamlit-dev-router.entrypoints=websecure"
      - "traefik.http.routers.streamlit-dev-router.tls.certresolver=myresolver"
    networks:
      - gencovery-network-dev
    container_name: codelab
    #GPU_CONFIG#


  # Front
  front:
    image: registry.gitlab.com/constellab/public/docker-registry/lab-front:${FRONT_VERSION}
    environment:
      - API_URL=https://glab.${VIRTUAL_HOST}
      - LAB_PROD_API_URL=https://glab.${VIRTUAL_HOST}
      - LAB_DEV_API_URL=https://glab-dev.${VIRTUAL_HOST}
      - CODELAB_URL=https://codelab.${VIRTUAL_HOST}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - SPACE_FRONT_URL=${SPACE_FRONT_URL}
      - SPACE_API_URL=${SPACE_API_URL}
      # TODO TO REMOVE ONCE all lab are on v0.8.2
      - CENTRAL_FRONT_URL=${SPACE_FRONT_URL}
      - CENTRAL_API_URL=${SPACE_API_URL}
      # end remove
      - COMMUNITY_FRONT_URL=${COMMUNITY_FRONT_URL}
      - COMMUNITY_API_URL=${COMMUNITY_API_URL}
      - CAPTCHA_SITE_KEY=${CAPTCHA_SITE_KEY}
    labels:
      - "traefik.enable=true"
      # Configure Host domain to port 81
      - "traefik.http.routers.front-router.rule=Host(`front.${VIRTUAL_HOST}`)"
      - "traefik.http.routers.front-router.service=front-service"
      - "traefik.http.services.front-service.loadbalancer.server.port=81"
      #Enable HTTPS
      - "traefik.http.routers.front-router.entrypoints=websecure"
      - "traefik.http.routers.front-router.tls.certresolver=myresolver"

      # Configure app to port 81
      - "traefik.http.routers.lab-router.rule=Host(`lab.${VIRTUAL_HOST}`)"
      - "traefik.http.routers.lab-router.service=lab-service"
      - "traefik.http.services.lab-service.loadbalancer.server.port=81"
      #Enable HTTPS
      - "traefik.http.routers.lab-router.entrypoints=websecure"
      - "traefik.http.routers.lab-router.tls.certresolver=myresolver"

      # Redirect http to https
      - "traefik.frontend.redirect.entryPoint=https"
    networks:
      - gencovery-network-prod
    container_name: front

  # GWS Core Production DB
  gws_core_prod_db:
    image: mariadb:10.7.4
    command: --max_allowed_packet=256M
    environment:
      - MYSQL_ROOT_PASSWORD=${GWS_CORE_PROD_DB_PASSWORD}
      - MYSQL_USER=gws_core
      - MYSQL_PASSWORD=${GWS_CORE_PROD_DB_PASSWORD}
      - MYSQL_DATABASE=gws_core
    volumes:
      - /app/gws_db/gws_core/prod/mariadb:/var/lib/mysql
    networks:
      - gencovery-network-prod
    container_name: gws_core_prod_db

  # GWS Core Development DB
  gws_core_dev_db:
    image: mariadb:10.7.4
    command: --max_allowed_packet=256M
    environment:
      - MYSQL_ROOT_PASSWORD=${GWS_CORE_DEV_DB_PASSWORD}
      - MYSQL_USER=gws_core
      - MYSQL_PASSWORD=${GWS_CORE_DEV_DB_PASSWORD}
      - MYSQL_DATABASE=gws_core
    volumes:
      - /app/gws_db/gws_core/dev/mariadb:/var/lib/mysql
    networks:
      - gencovery-network-dev
    container_name: gws_core_dev_db

  # GWS Test db
  test_gws_dev_db:
    image: mariadb:10.7.4
    command: --max_allowed_packet=256M
    environment:
      - MYSQL_ROOT_PASSWORD=gencovery
      - MYSQL_USER=test_gws
      - MYSQL_PASSWORD=gencovery
      - MYSQL_DATABASE=test_gws
    networks:
      - gencovery-network-dev
    container_name: test_gws_dev_db

  # GWS Biota Production DB
  gws_biota_db:
    image: mariadb:10.7.4
    command: --max_allowed_packet=256M
    environment:
      - MYSQL_ROOT_PASSWORD=gencovery
      - MYSQL_USER=gws_biota
      - MYSQL_PASSWORD=gencovery
      - MYSQL_DATABASE=gws_biota
    volumes:
      - /app/gws_db/gws_biota/mariadb:/var/lib/mysql
    networks:
      - gencovery-network-prod
      - gencovery-network-dev
    container_name: gws_biota_db


networks:
  gencovery-network-dev:
    external: true
  gencovery-network-prod:
    external: true
