# Docker compose file used in dev (local env). It removes the volumes and traefik config

version: "3"

services:

  # Production Glab
  glab:
    image: registry.gitlab.com/gencovery/infra/gpm/glab-${IMAGE_SUFFIX}:${GLAB_TAG}
    environment:
      - LAB_ID=1
      - LAB_NAME=MyLab
      - LAB_MODE=prod
      - LAB_ENVIRONMENT=PROD
      - LAB_PROD_API_URL=http://localhost:3000
      - LAB_DEV_API_URL=http://localhost:3000
      - CENTRAL_API_KEY=
      - CENTRAL_API_URL=
      - FRONT_URL=http://localhost:4200
      - FRONT_VERSION=
      - CONDA_VERSION=latest
      - GPU=${GPU}
      - VIRTUAL_HOST=
      - BIOTA_BIODATA_DIR=/data/gws_biota/biodata/
      - GWS_GIT_LOGIN=${GWS_GIT_LOGIN}
      - GWS_GIT_PWD=${GWS_GIT_PWD}
      # GWS_CORE database
      - GWS_CORE_DB_HOST=local_gws_core_prod_db
      - GWS_CORE_DB_USER=gws_core
      - GWS_CORE_DB_PASSWORD=gencovery
      - GWS_CORE_DB_NAME=gws_core
      - GWS_CORE_DB_PORT=3306
      # GWS_BIOTA database
      - GWS_BIOTA_DB_HOST=local_gws_biota_db
      - GWS_BIOTA_DB_USER=gws_biota
      - GWS_BIOTA_DB_PASSWORD=gencovery
      - GWS_BIOTA_DB_NAME=gws_biota
      - GWS_BIOTA_DB_PORT=3306
    depends_on:
      - gws_core_prod_db
      - gws_biota_db
    volumes:
      - lab-manager-config:/conf
      - lab-manager-prod-lab:/lab

    networks:
      - local_gencovery-network-prod
    container_name: local_glab

  # Codelab
  codelab:
    image: registry.gitlab.com/gencovery/infra/gpm/codelab-${IMAGE_SUFFIX}:${GLAB_TAG}
    environment:
      - LAB_ID=${LAB_ID}
      - LAB_NAME=${LAB_NAME}
      - LAB_MODE=dev
      - LAB_ENVIRONMENT=PROD
      - LAB_PROD_API_URL=https://glab-prod.${VIRTUAL_HOST}
      - LAB_DEV_API_URL=https://glab-dev.${VIRTUAL_HOST}
      - FRONT_URL=http://localhost:80
      - FRONT_VERSION=${FRONT_VERSION}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - BIOTA_BIODATA_DIR=/data/gws_biota/biodata/
      - CONDA_VERSION=latest
      - GPU=${GPU}
      - GWS_GIT_LOGIN=${GWS_GIT_LOGIN}
      - GWS_GIT_PWD=${GWS_GIT_PWD}
      # GWS_CORE database
      - GWS_CORE_DB_HOST=local_gws_core_dev_db
      - GWS_CORE_DB_USER=gws_core
      - GWS_CORE_DB_PASSWORD=gencovery
      - GWS_CORE_DB_NAME=gws_core
      - GWS_CORE_DB_PORT=3306
      # Test database
      - GWS_TEST_DB_HOST=local_test_gws_dev_db
      - GWS_TEST_DB_USER=test_gws
      - GWS_TEST_DB_PASSWORD=gencovery
      - GWS_TEST_DB_NAME=test_gws
      - GWS_TEST_DB_PORT=3306
      # GWS_BIOTA database
      - GWS_BIOTA_DB_HOST=local_gws_biota_db
      - GWS_BIOTA_DB_USER=gws_biota
      - GWS_BIOTA_DB_PASSWORD=gencovery
      - GWS_BIOTA_DB_NAME=gws_biota
      - GWS_BIOTA_DB_PORT=3306
    volumes:
      - lab-manager-config:/conf
      - lab-manager-dev-lab:/lab
    depends_on:
      - gws_core_dev_db
      - gws_biota_db
    networks:
      - local_gencovery-network-dev
    container_name: local_codelab
    ports: 
      - 8083:8080


  # Front
  front:
    image: registry.gitlab.com/gencovery/core/monorepo/lab-front:latest
    environment:
      - API_URL=https://local_glab-prod.${VIRTUAL_HOST}/
      - LAB_PROD_API_URL=https://local_glab-prod.${VIRTUAL_HOST}/
      - LAB_DEV_API_URL=https://local_glab-dev.${VIRTUAL_HOST}/
      - CODE_SERVER_URL=https://local_codelab.${VIRTUAL_HOST}
      - VIRTUAL_HOST=
    networks:
      - local_gencovery-network-prod
    container_name: local_front
    ports: 
      - 89:81

  # GWS Core Production DB
  gws_core_prod_db:
    image: mariadb:10.7.4
    command: --max_allowed_packet=256M
    environment:
      - MYSQL_ROOT_PASSWORD=gencovery
      - MYSQL_USER=gws_core
      - MYSQL_PASSWORD=gencovery
      - MYSQL_DATABASE=gws_core
    networks:
      - local_gencovery-network-prod
    container_name: local_gws_core_prod_db

  # GWS Core Development DB
  gws_core_dev_db:
    image: mariadb:10.7.4
    command: --max_allowed_packet=256M
    environment:
      - MYSQL_ROOT_PASSWORD=gencovery
      - MYSQL_USER=gws_core
      - MYSQL_PASSWORD=gencovery
      - MYSQL_DATABASE=gws_core
    networks:
      - local_gencovery-network-dev
    container_name: local_gws_core_dev_db

  # GWS Test db
  test_gws_dev_db:
    image: mariadb:10.7.4
    command: --max_allowed_packet=256M
    environment:
      - MYSQL_ROOT_PASSWORD=gencovery
      - MYSQL_USER=test_gws
      - MYSQL_PASSWORD=gencovery
      - MYSQL_DATABASE=test_gws
    networks:
      - local_gencovery-network-dev
    container_name: local_test_gws_dev_db

  # GWS Biota Production DB
  gws_biota_db:
    image: mariadb:10.7.4
    command: --max_allowed_packet=256M
    environment:
      - MYSQL_ROOT_PASSWORD=gencovery
      - MYSQL_USER=gws_biota
      - MYSQL_PASSWORD=gencovery
      - MYSQL_DATABASE=gws_biota
    networks:
      - local_gencovery-network-prod
      - local_gencovery-network-dev
    container_name: local_gws_biota_db
    volumes:
      - lab-manager-biota:/var/lib/mysql


networks:
  local_gencovery-network-dev:
    external: false
  local_gencovery-network-prod:
    external: false

# the volume names are the same as the one in the dockerlab local docker-compose.yml
# this is because volume are relative to host machine and not docker image
volumes:
  lab-manager-config:
    external: true
  lab-manager-biota:
    external: true
  lab-manager-prod-lab:
    external: true
  lab-manager-dev-lab:
    external: true
