version: "3"

services:
  # /!\ WARNING /!\
  # As docker execute inside a docker container, the volume here are relative to the host machine and not the container
  # On /app/prod/lab:/lab, /app/prod/lab refers to the host machine and not the container that run the docker-compose
  # Production Glab
  glab:
    image: registry.gitlab.com/gencovery/infra/gpm/glab-${IMAGE_SUFFIX}:${GLAB_TAG}
    environment:
      - LAB_ID=${LAB_ID}
      - LAB_NAME=${LAB_NAME}
      - LAB_MODE=prod
      - LAB_ENVIRONMENT=PROD
      - LAB_PROD_API_URL=https://glab.${VIRTUAL_HOST}
      - LAB_DEV_API_URL=https://glab-dev.${VIRTUAL_HOST}
      - CENTRAL_API_KEY=${CENTRAL_API_KEY}
      - CENTRAL_API_URL=${CENTRAL_API_URL}
      - FRONT_URL=https://front.${VIRTUAL_HOST}
      - FRONT_VERSION=${FRONT_VERSION}
      - CONDA_VERSION=latest
      - GPU=${GPU}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - BIOTA_BIODATA_DIR=/data/gws_biota/biodata/
      - GWS_GIT_LOGIN=${GWS_GIT_LOGIN}
      - GWS_GIT_PWD=${GWS_GIT_PWD}
      - GWS_CORE_DB_PASSWORD=${GWS_CORE_PROD_DB_PASSWORD}
      # GWS_CORE database
      - GWS_CORE_DB_HOST=gws_core_prod_db
      - GWS_CORE_DB_USER=gws_core
      - GWS_CORE_DB_PASSWORD=${GWS_CORE_DEV_DB_PASSWORD}
      - GWS_CORE_DB_NAME=gws_core
      - GWS_CORE_DB_PORT=3306
      # GWS_BIOTA database
      - GWS_BIOTA_DB_HOST=gws_biota_db
      - GWS_BIOTA_DB_USER=gws_biota
      - GWS_BIOTA_DB_PASSWORD=gencovery
      - GWS_BIOTA_DB_NAME=gws_biota
      - GWS_BIOTA_DB_PORT=3306
    depends_on:
      - gws_core_prod_db
      - gws_biota_db
    volumes:
      - /app/prod/lab:/lab
      - /app/prod/logs:/logs
      - /app/prod/settings/glab:/conf/settings
      - /app/conf/config.json:/conf/config.json:ro
      - /app/prod/data:/data
    labels:
      - "traefik.enable=true"
      # Config for the HTTPS glab domain to port 8080
      - "traefik.http.routers.glab-router.rule=host(`glab.${VIRTUAL_HOST}`)"
      - "traefik.http.routers.glab-router.service=glab-service"
      - "traefik.http.services.glab-service.loadbalancer.server.port=3000"
      # Enable HTTPS
      - "traefik.http.routers.glab-router.entrypoints=websecure"
      - "traefik.http.routers.glab-router.tls.certresolver=myresolver"
    networks:
      - gencovery-network-prod
    restart: on-failure:5
    container_name: glab

  # Codelab
  codelab:
    image: registry.gitlab.com/gencovery/infra/gpm/codelab-${IMAGE_SUFFIX}:${GLAB_TAG}
    environment:
      - LAB_ID=${LAB_ID}
      - LAB_NAME=${LAB_NAME}
      - LAB_MODE=dev
      - LAB_ENVIRONMENT=PROD
      - LAB_PROD_API_URL=https://glab.${VIRTUAL_HOST}
      - LAB_DEV_API_URL=https://glab-dev.${VIRTUAL_HOST}
      - FRONT_URL=https://front.${VIRTUAL_HOST}
      - FRONT_VERSION=${FRONT_VERSION}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - BIOTA_BIODATA_DIR=/data/gws_biota/biodata/
      - CONDA_VERSION=latest
      - GPU=${GPU}
      - GWS_GIT_LOGIN=${GWS_GIT_LOGIN}
      - GWS_GIT_PWD=${GWS_GIT_PWD}
      # GWS_CORE database
      - GWS_CORE_DB_HOST=gws_core_dev_db
      - GWS_CORE_DB_USER=gws_core
      - GWS_CORE_DB_PASSWORD=${GWS_CORE_DEV_DB_PASSWORD}
      - GWS_CORE_DB_NAME=gws_core
      - GWS_CORE_DB_PORT=3306
      # Test database
      - GWS_TEST_DB_HOST=test_gws_dev_db
      - GWS_TEST_DB_USER=test_gws
      - GWS_TEST_DB_PASSWORD=gencovery
      - GWS_TEST_DB_NAME=test_gws
      - GWS_TEST_DB_PORT=3306
      # GWS_BIOTA database
      - GWS_BIOTA_DB_HOST=gws_biota_db
      - GWS_BIOTA_DB_USER=gws_biota
      - GWS_BIOTA_DB_PASSWORD=gencovery
      - GWS_BIOTA_DB_NAME=gws_biota
      - GWS_BIOTA_DB_PORT=3306
    depends_on:
      - gws_core_dev_db
      - gws_biota_db
    volumes:
      - /app/dev/lab:/lab
      - /app/dev/logs:/logs
      - /app/dev/data:/data
      - /app/dev/settings/glab:/conf/settings
      - /app/conf/config.json:/conf/config.json:ro
    labels:
      - "traefik.enable=true"
      # Config for the HTTPS codelab domain to port 8080
      - "traefik.http.routers.codelab-router.rule=host(`codelab.${VIRTUAL_HOST}`)"
      - "traefik.http.routers.codelab-router.service=codelab-service"
      - "traefik.http.services.codelab-service.loadbalancer.server.port=8080"
      # Enable HTTPS
      - "traefik.http.routers.codelab-router.entrypoints=websecure"
      - "traefik.http.routers.codelab-router.tls.certresolver=myresolver"
      # secure the access with htpasswd
      - "traefik.http.routers.codelab-router.middlewares=basic-auth"
      - "traefik.http.middlewares.basic-auth.basicauth.users=${HT_PASSWD}"

      # Config for the HTTPS gws run inside the CODELAB domain to port 3000
      - "traefik.http.routers.glab-dev-router.rule=host(`glab-dev.${VIRTUAL_HOST}`)"
      - "traefik.http.routers.glab-dev-router.service=glab-dev-service"
      - "traefik.http.services.glab-dev-service.loadbalancer.server.port=3000"
      # Enable HTTPS
      - "traefik.http.routers.glab-dev-router.entrypoints=websecure"
      - "traefik.http.routers.glab-dev-router.tls.certresolver=myresolver"
    networks:
      - gencovery-network-dev
    container_name: codelab


  # Front
  front:
    image: registry.gitlab.com/gencovery/core/monorepo/lab-front:${FRONT_VERSION}
    environment:
      - API_URL=https://glab.${VIRTUAL_HOST}/
      - LAB_PROD_API_URL=https://glab.${VIRTUAL_HOST}/
      - LAB_DEV_API_URL=https://glab-dev.${VIRTUAL_HOST}/
      - CODE_SERVER_URL=https://codelab.${VIRTUAL_HOST}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - CENTRAL_FRONT_URL=${CENTRAL_FRONT_URL}
      - CENTRAL_API_URL=${CENTRAL_API_URL}
      - HUB_FRONT_URL=${HUB_FRONT_URL}
    labels:
      - "traefik.enable=true"
      # Configure Host domain to port 81
      - "traefik.http.routers.front-router.rule=Host(`front.${VIRTUAL_HOST}`)"
      - "traefik.http.routers.front-router.service=front-service"
      - "traefik.http.services.front-service.loadbalancer.server.port=81"
      #Enable HTTPS
      - "traefik.http.routers.front-router.entrypoints=websecure"
      - "traefik.http.routers.front-router.tls.certresolver=myresolver"
      - "traefik.frontend.redirect.entryPoint=https"
    networks:
      - gencovery-network-prod
    container_name: front

  # GWS Core Production DB
  gws_core_prod_db:
    image: mariadb:10.7.4
    command: --max_allowed_packet=256M
    environment:
      - MYSQL_ROOT_PASSWORD=${GWS_CORE_PROD_DB_PASSWORD}
      - MYSQL_USER=gws_core
      - MYSQL_PASSWORD=${GWS_CORE_PROD_DB_PASSWORD}
      - MYSQL_DATABASE=gws_core
    volumes:
      - /gws_db/gws_core/prod/mariadb:/var/lib/mysql
    networks:
      - gencovery-network-prod
    container_name: gws_core_prod_db

  # GWS Core Development DB
  gws_core_dev_db:
    image: mariadb:10.7.4
    command: --max_allowed_packet=256M
    environment:
      - MYSQL_ROOT_PASSWORD=${GWS_CORE_DEV_DB_PASSWORD}
      - MYSQL_USER=gws_core
      - MYSQL_PASSWORD=${GWS_CORE_DEV_DB_PASSWORD}
      - MYSQL_DATABASE=gws_core
    volumes:
      - /gws_db/gws_core/dev/mariadb:/var/lib/mysql
    networks:
      - gencovery-network-dev
    container_name: gws_core_dev_db

  # GWS Test db
  test_gws_dev_db:
    image: mariadb:10.7.4
    command: --max_allowed_packet=256M
    environment:
      - MYSQL_ROOT_PASSWORD=gencovery
      - MYSQL_USER=test_gws
      - MYSQL_PASSWORD=gencovery
      - MYSQL_DATABASE=test_gws
    networks:
      - gencovery-network-dev
    container_name: test_gws_dev_db

  # GWS Biota Production DB
  gws_biota_db:
    image: mariadb:10.7.4
    command: --max_allowed_packet=256M
    environment:
      - MYSQL_ROOT_PASSWORD=gencovery
      - MYSQL_USER=gws_biota
      - MYSQL_PASSWORD=gencovery
      - MYSQL_DATABASE=gws_biota
    volumes:
      - /gws_db/gws_biota/mariadb:/var/lib/mysql
    networks:
      - gencovery-network-prod
      - gencovery-network-dev
    container_name: gws_biota_db


networks:
  gencovery-network-dev:
    external: true
  gencovery-network-prod:
    external: true
