# Docker compose file used in dev (local env). It removes the volumes and traefik config

version: "3"

services:

  # Production Glab
  glab:
    image: glab:latest
    environment:
      - LAB_ID=1
      - LAB_NAME=MyLab
      - LAB_MODE=prod
      - LAB_ENVIRONMENT=PROD
      - LAB_PROD_API_URL=http://localhost:3000
      - LAB_DEV_API_URL=http://localhost:3000
      - CENTRAL_API_KEY=
      - CENTRAL_API_URL=
      - FRONT_URL=http://localhost:4200
      - FRONT_VERSION=
      - CONDA_VERSION=latest
      - GPU=${GPU}
      - VIRTUAL_HOST=
      - BIOTA_BIODATA_DIR=/data/gws_biota/biodata/
      - UPDATE_GIT_BRICKS=1
      - GWS_GIT_LOGIN=
      - GWS_GIT_PWD=
    depends_on:
      - gws_core_prod_db
      - gws_biota_db
    volumes:
      # - /var/log/apt:/lab
      # - /app/prod/lab:/lab
      # - /app/prod/logs:/logs
      # - /app/prod/settings/glab:/conf/settings
      # - /app/conf/config.json:/conf/config.json:ro
      # - /app/prod/data:/data
      # - C:\Users\benji\.ssh\gencovery-gitlab:/root/.ssh/id_rsa
      - lab-app:/lab
      # - lab-data:/data
      # - lab-logs:/logs
      # - lab-settings:/conf/settings
      # - lab-config:/conf

    # networks:
      # - gencovery-network-prod
    container_name: glab

  # Codelab
  codelab:
    image: registry.gitlab.com/gencovery/infra/gpm/codelab-${IMAGE_SUFFIX}:${GLAB_TAG}
    environment:
      - LAB_ID=${LAB_ID}
      - LAB_NAME=${LAB_NAME}
      - LAB_MODE=dev
      - LAB_ENVIRONMENT=PROD
      - LAB_PROD_API_URL=https://glab-prod.${VIRTUAL_HOST}
      - LAB_DEV_API_URL=https://glab-dev.${VIRTUAL_HOST}
      - FRONT_URL=http://localhost:4200
      - FRONT_VERSION=${FRONT_VERSION}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - BIOTA_BIODATA_DIR=/data/gws_biota/biodata/
      - CONDA_VERSION=latest
      - GPU=${GPU}
      - UPDATE_GIT_BRICKS=${UPDATE_GIT_BRICKS}
      - GWS_GIT_LOGIN=${GWS_GIT_LOGIN}
      - GWS_GIT_PWD=${GWS_GIT_PWD}
    volumes:
      # use the named volume lab to improve performance of the local docker-compose of dockerlab project
      # volume is available at \\wsl.localhost\docker-desktop-data\version-pack-data\community\docker\volumes\local_lab\_data
      - lab-app:/lab
      - lab-data:/data
      - lab-logs:/logs
      - lab-settings:/conf/settings
      # - lab-config:/conf/config.json:ro
      # Share git credentials by sharing ssh private key
      # - C:\Users\benji\.ssh\gencovery-gitlab:/root/.ssh/id_rsa
    depends_on:
      - gws_core_dev_db
      - gws_biota_db
    # networks:
    #   - gencovery-network-dev
    container_name: codelab


  # Front
  front:
    image: registry.gitlab.com/gencovery/core/monorepo/lab-front:latest
    environment:
      - API_URL=https://glab-prod.${VIRTUAL_HOST}/
      - LAB_PROD_API_URL=https://glab-prod.${VIRTUAL_HOST}/
      - LAB_DEV_API_URL=https://glab-dev.${VIRTUAL_HOST}/
      - CODE_SERVER_URL=https://codelab.${VIRTUAL_HOST}
      - VIRTUAL_HOST=
    # networks:
    #   - gencovery-network-prod
    container_name: front

  # GWS Core Production DB
  gws_core_prod_db:
    image: mariadb:10.7.4
    command: --max_allowed_packet=256M
    environment:
      - MYSQL_ROOT_PASSWORD=gencovery
      - MYSQL_USER=gws_core
      - MYSQL_PASSWORD=gencovery
      - MYSQL_DATABASE=gws_core
    # networks:
    #   - gencovery-network-prod
    container_name: gws_core_prod_db

  # GWS Core Development DB
  gws_core_dev_db:
    image: mariadb:10.7.4
    command: --max_allowed_packet=256M
    environment:
      - MYSQL_ROOT_PASSWORD=gencovery
      - MYSQL_USER=gws_core
      - MYSQL_PASSWORD=gencovery
      - MYSQL_DATABASE=gws_core
    # networks:
    #   - gencovery-network-dev
    container_name: gws_core_dev_db

  # GWS Test db
  test_gws_dev_db:
    image: mariadb:10.7.4
    command: --max_allowed_packet=256M
    environment:
      - MYSQL_ROOT_PASSWORD=gencovery
      - MYSQL_USER=test_gws
      - MYSQL_PASSWORD=gencovery
      - MYSQL_DATABASE=test_gws
    # networks:
    #   - gencovery-network-dev
    container_name: test_gws_dev_db

  # GWS Biota Production DB
  gws_biota_db:
    image: mariadb:10.7.4
    command: --max_allowed_packet=256M
    environment:
      - MYSQL_ROOT_PASSWORD=gencovery
      - MYSQL_USER=gws_biota
      - MYSQL_PASSWORD=gencovery
      - MYSQL_DATABASE=gws_biota
    # networks:
    #   - gencovery-network-prod
    #   - gencovery-network-dev
    container_name: gws_biota_db


# networks:
#   gencovery-network-dev:
#     external: true
#   gencovery-network-prod:
#     external: true

volumes:
  lab-app:
  lab-data:
  lab-logs:
  lab-settings:
  lab-config:
  # new new volume tt link to /var/log folder
  lab-new-volume:
    driver_opts:
      type: none
      device: /var/log
      o: bind