# Docker compose file used in dev (local env). It removes the volumes and traefik config
name: lab-manager-dev
services:
  # Production Glab
  glab:
    image: constellab/glab:${TAG_PREFIX}${GLAB_TAG}
    environment:
      - LAB_ID=${LAB_ID}
      - LAB_NAME=${LAB_NAME}
      - LAB_MODE=${LAB_MODE}
      - LAB_ENVIRONMENT=${LAB_ENVIRONMENT}
      - LAB_PROD_API_URL=http://localhost:3100
      - LAB_DEV_API_URL=http://codelab:3000
      - SPACE_API_KEY=${SPACE_PROD_API_KEY}
      - SPACE_API_URL=${SPACE_API_URL}
      - SPACE_FRONT_URL=${SPACE_FRONT_URL}
      - FRONT_URL=http://localhost:89
      - FRONT_VERSION=${FRONT_VERSION}
      - GPU=${GPU}
      - VIRTUAL_HOST=
      - BIOTA_BIODATA_DIR=/data/gws_biota/biodata/
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # COMMUNITY
      - COMMUNITY_API_URL=${COMMUNITY_API_URL}
      - COMMUNITY_FRONT_URL=${COMMUNITY_FRONT_URL}
      - COMMUNITY_API_KEY=${COMMUNITY_API_KEY}
      # GWS_CORE database
      - GWS_CORE_DB_HOST=gws_core_prod_db
      - GWS_CORE_DB_USER=gws_core
      - GWS_CORE_DB_PASSWORD=${GWS_CORE_PROD_DB_PASSWORD}
      - GWS_CORE_DB_NAME=gws_core
      - GWS_CORE_DB_PORT=3306
      # GWS_BIOTA database
      - GWS_BIOTA_DB_HOST=gws_biota_db
      - GWS_BIOTA_DB_USER=gws_biota
      - GWS_BIOTA_DB_PASSWORD=gencovery
      - GWS_BIOTA_DB_NAME=gws_biota
      - GWS_BIOTA_DB_PORT=3306
      # TODO to remove once labs are on v 0.15.0
      - STREAMLIT_APP_SERVER_PORT=8501
      - STREAMLIT_APP_SERVER_HOST=http://localhost.8501
    depends_on:
      - gws_core_prod_db
      - gws_biota_db
    volumes:
      # this volume include conf and settings
      - lab-manager-config:/conf
      # volume for prod lab
      - lab-manager-prod-lab:/lab
      - lab-manager-prod-data:/data
    networks:
      - gencovery-network-prod
    container_name: glab
    ports:
      - 3100:3000
    #GPU_CONFIG#

  # Codelab
  codelab:
    image: constellab/codelab:${TAG_PREFIX}${GLAB_TAG}
    environment:
      # The environment variables are also define in gpm repository
      # in codelab-init-ssh.sh file.
      # When a new variable is added or a variable is deleted,
      # the file codelab-init-ssh.sh should be updated too.
      - LAB_ID=${LAB_ID}
      - LAB_NAME=${LAB_NAME}
      - LAB_MODE=dev
      - LAB_ENVIRONMENT=${LAB_ENVIRONMENT}
      - LAB_PROD_API_URL=http://glab:3000
      - LAB_DEV_API_URL=http://localhost:3100
      - SPACE_API_KEY=${SPACE_PROD_API_KEY}
      - SPACE_API_URL=${SPACE_API_URL}
      - SPACE_FRONT_URL=${SPACE_FRONT_URL}
      - FRONT_URL=http://localhost:89
      - FRONT_VERSION=${FRONT_VERSION}
      - GPU=${GPU}
      - VIRTUAL_HOST=
      - BIOTA_BIODATA_DIR=/data/gws_biota/biodata/
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # COMMUNITY
      - COMMUNITY_API_URL=${COMMUNITY_API_URL}
      - COMMUNITY_FRONT_URL=${COMMUNITY_FRONT_URL}
      - COMMUNITY_API_KEY=${COMMUNITY_API_KEY}
      # GWS_CORE database
      - GWS_CORE_DB_HOST=gws_core_dev_db
      - GWS_CORE_DB_USER=gws_core
      - GWS_CORE_DB_PASSWORD=${GWS_CORE_DEV_DB_PASSWORD}
      - GWS_CORE_DB_NAME=gws_core
      - GWS_CORE_DB_PORT=3306
      # Test database
      - GWS_TEST_DB_HOST=test_gws_dev_db
      - GWS_TEST_DB_USER=test_gws
      - GWS_TEST_DB_PASSWORD=gencovery
      - GWS_TEST_DB_NAME=test_gws
      - GWS_TEST_DB_PORT=3306
      # GWS_BIOTA database
      - GWS_BIOTA_DB_HOST=gws_biota_db
      - GWS_BIOTA_DB_USER=gws_biota
      - GWS_BIOTA_DB_PASSWORD=gencovery
      - GWS_BIOTA_DB_NAME=gws_biota
      - GWS_BIOTA_DB_PORT=3306
      # TODO to remove once labs are on v 0.15.0
      - STREAMLIT_APP_SERVER_PORT=8501
      - STREAMLIT_APP_SERVER_HOST=http://localhost.8501
    volumes:
      - lab-manager-config:/conf
      - lab-manager-dev-lab:/lab
    depends_on:
      - gws_core_dev_db
      - gws_biota_db
    networks:
      - gencovery-network-dev
    container_name: codelab
    ports:
      - 8083:8080
      # enable ssh server on this port
      - 2222:2222
    #GPU_CONFIG#

  # Front
  front:
    image: constellab/lab-front:latest
    environment:
      - API_URL=http://localhost:3100
      - LAB_PROD_API_URL=http://localhost:3100
      - LAB_DEV_API_URL=http://localhost:3100
      - CODELAB_URL=http://localhost:8083
      - VIRTUAL_HOST=
      - SPACE_FRONT_URL=${SPACE_FRONT_URL}
      - SPACE_API_URL=${SPACE_API_URL}
      # same dev and prod url
      - PROD_FRONT_URLS=http://localhost:89
      - DEV_FRONT_URLS=http://localhost:89
      - COMMUNITY_FRONT_URL=${COMMUNITY_FRONT_URL}
      - COMMUNITY_API_URL=${COMMUNITY_API_URL}
      - CAPTCHA_SITE_KEY=
    networks:
      - gencovery-network-prod
    container_name: front
    ports:
      - 89:81

  # GWS Core Production DB
  gws_core_prod_db:
    image: mariadb:10.7.4
    command: --max_allowed_packet=256M
    environment:
      - MYSQL_ROOT_PASSWORD=${GWS_CORE_PROD_DB_PASSWORD}
      - MYSQL_USER=gws_core
      - MYSQL_PASSWORD=${GWS_CORE_PROD_DB_PASSWORD}
      - MYSQL_DATABASE=gws_core
    volumes:
      - lab-manager-prod-db:/var/lib/mysql
    networks:
      - gencovery-network-prod
    container_name: gws_core_prod_db
    ports:
      - 3406:3306

  # GWS Core Development DB
  gws_core_dev_db:
    image: mariadb:10.7.4
    command: --max_allowed_packet=256M
    environment:
      - MYSQL_ROOT_PASSWORD=${GWS_CORE_DEV_DB_PASSWORD}
      - MYSQL_USER=gws_core
      - MYSQL_PASSWORD=${GWS_CORE_DEV_DB_PASSWORD}
      - MYSQL_DATABASE=gws_core
    volumes:
      - lab-manager-dev-db:/var/lib/mysql
    networks:
      - gencovery-network-dev
    container_name: gws_core_dev_db
    ports:
      - 3407:3306

  # GWS Test db
  test_gws_dev_db:
    image: mariadb:10.7.4
    command: --max_allowed_packet=256M
    environment:
      - MYSQL_ROOT_PASSWORD=gencovery
      - MYSQL_USER=test_gws
      - MYSQL_PASSWORD=gencovery
      - MYSQL_DATABASE=test_gws
    networks:
      - gencovery-network-dev
    container_name: test_gws_dev_db
    ports:
      - 3408:3306

  # GWS Biota Production DB
  gws_biota_db:
    image: mariadb:10.7.4
    command: --max_allowed_packet=256M
    environment:
      - MYSQL_ROOT_PASSWORD=gencovery
      - MYSQL_USER=gws_biota
      - MYSQL_PASSWORD=gencovery
      - MYSQL_DATABASE=gws_biota
    networks:
      - gencovery-network-prod
      - gencovery-network-dev
    container_name: gws_biota_db
    volumes:
      - lab-manager-biota:/var/lib/mysql
    ports:
      - 3409:3306

networks:
  gencovery-network-dev:
    external: true
  gencovery-network-prod:
    external: true

# the volume names are the same as the one in the lab-configurer local docker-compose.yml
# this is because volume are relative to host machine and not docker image
volumes:
  lab-manager-config:
    external: true
  lab-manager-prod-db:
    external: true
  lab-manager-dev-db:
    external: true
  lab-manager-biota:
    external: true
  lab-manager-prod-lab:
    external: true
  lab-manager-prod-data:
    external: true
  lab-manager-dev-lab:
    external: true
