# Action to build image from dockerfile, then push it to dockerhub to constellab organization

name: Publish Docker image

on:
  push:
    tags:
      - '*'

env:
  IMAGE_NAME: constellab/lab-manager

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6.0.2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.7.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME}}
          tags: |
            type=ref,event=tag

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6.19.2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            LAB_MANAGER_VERSION=${{ github.ref_name }}

      # step to set the docker image description from docker_hub_README.md
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4.0.2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.IMAGE_NAME}}
          readme-filepath: ./docker_hub_README.md
